#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# RUTAS PARA CONTROLADOR: USER #

user:
    path: /user
    controller: App\Controller\UserController::index
    methods: [GET]

user_profile:
    path: /user/profile/{id}
    controller: App\Controller\UserController::myProfile
    methods: [GET]

register:
    path: /register
    controller: App\Controller\UserController::create
    methods: [POST]

login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [POST]

user_edit:
    path: /user/edit
    controller: App\Controller\UserController::edit
    methods: [PUT]

user_upload_image:
    path: /user/upload-image
    controller: App\Controller\UserController::uploadImage
    methods: [POST]

user_total:
    path: /user/total
    controller: App\Controller\UserController::allUsers
    methods: [GET]

    
# RUTAS PARA CONTROLADOR: EVENT #

event:
    path: /event
    controller: App\Controller\EventController::index

event_new:
    path: /event/new
    controller: App\Controller\EventController::create
    methods: [POST]

event_edit:
    path: /event/edit/{id}
    controller: App\Controller\EventController::create
    methods: [PUT]

event_list:
    path: /event/list
    controller: App\Controller\EventController::eventos
    methods: [GET]

event_total:
    path: /event/total
    controller: App\Controller\EventController::allEventos
    methods: [GET]

event_detail:
    path: /event/detail/{id}
    controller: App\Controller\EventController::event
    methods: [GET]

event_remove:
    path: /event/remove/{id}
    controller: App\Controller\EventController::remove
    methods: [DELETE]

    # RUTAS PARA CONTROLADOR: COMMENT #

comment:
    path: /comment
    controller: App\Controller\CommentController::index

comment_new:
    path: /comment/new
    controller: App\Controller\CommentController::create
    methods: [POST]

comment_edit:
    path: /comment/edit/{id}
    controller: App\Controller\CommentController::create
    methods: [PUT]

comment_remove:
    path: /comment/remove/{id}
    controller: App\Controller\CommentController::remove
    methods: [DELETE]

comment_list:
    path: /comment/list/{id}
    controller: App\Controller\CommentController::listComments
    methods: [GET]